// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-6q3yEw6oChdj-1T3joAl24LAtsNUC0I',
    appId: '1:485962101208:web:b152c0288cef5b136f82ad',
    messagingSenderId: '485962101208',
    projectId: 'food-cort-500c9',
    authDomain: 'food-cort-500c9.firebaseapp.com',
    storageBucket: 'food-cort-500c9.appspot.com',
    measurementId: 'G-6NE82FCHB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOSlG7YrCsh_fUHFHGIA5nAbbMQMIHPKs',
    appId: '1:485962101208:android:c1387ea253255f6a6f82ad',
    messagingSenderId: '485962101208',
    projectId: 'food-cort-500c9',
    storageBucket: 'food-cort-500c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9j_oJeV8NmlXdXY2giPMjiXAcoZtvzW0',
    appId: '1:485962101208:ios:060928e147dedfad6f82ad',
    messagingSenderId: '485962101208',
    projectId: 'food-cort-500c9',
    storageBucket: 'food-cort-500c9.appspot.com',
    iosClientId: '485962101208-9rnn9cq8qsf7hcj8j4ep75g9osp8m64l.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodcort',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9j_oJeV8NmlXdXY2giPMjiXAcoZtvzW0',
    appId: '1:485962101208:ios:21cca6f70e7b915a6f82ad',
    messagingSenderId: '485962101208',
    projectId: 'food-cort-500c9',
    storageBucket: 'food-cort-500c9.appspot.com',
    iosClientId: '485962101208-iuvddef9s45bmg4ra2lh94stquvnop28.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodcort.RunnerTests',
  );
}
